### ISSUE TITLE
No output on MacOS Big Sur

### ISSUE THREAD

**Issue by agnf** [elgatosf/streamdeck-cpu#15]
after updating MacOS to the latest version (Big Sur) the CPU output stopped working. I only get the square image without any percentage output.

**Comment by elgatosystems** [comment]
Could you please try to:

- Open the `More Actions…` window
- Uninstall and reinstall the CPU plugin

Does that help?

**Comment by agnf** [comment]
reinstalling did the trick. Thanks. Case closed.
