### ISSUE TITLE
CodePath is required but absent in manifest.json

### ISSUE THREAD

**Issue by intrueder** [elgatosf/streamdeck-cpu#5]
According to documentation https://developer.elgato.com/documentation/stream-deck/sdk/manifest/ `CodePath` is required, and DistributionTool can't be run against such manifest.json

**Comment by Timac** [comment]
Thanks for the report. This manifest indeed doesn't contain a `CodePath`.
However it contains both `CodePathMac` and `CodePathWin` which override `CodePath` respectively for macOS and Windows. The manifest is thus valid for DistributionTool.

So this is not really an issue but instead something we could clarify in the documentation.
