### ISSUE TITLE
No CPU % Shown

### ISSUE THREAD

**Issue by leftbrainstuff** [elgatosf/streamdeck-cpu#6]
This CPU plugin worked fine initially. Next day no percentage is shown after reboot of macbook pro. (reboot for other reasons) Removed and reinstalled but no change.

Running it through a USB hub that I can disable individual usb ports at night.

**Comment by Timac** [comment]
Since you reported the issue, we released some new Stream Deck versions which might have fixed the issue. Could you please try Stream Deck 4.7 and let us know if you still see this problem?

Thanks in advance!
