### ISSUE TITLE
Can this file be reformatted?

### ISSUE THREAD

**Issue by matkatmusic** [elgatosf/streamdeck-cpu#7]
https://github.com/elgatosf/streamdeck-cpu/blob/0a9c2557fbe6f829f3456a272672f810291948b3/Sources/macOS/CpuUsageHelper.cpp#L17

the indentation in this file is all over the place and it's tough to read when trying to analyze the example.

**Comment by Timac** [comment]
Thanks for the bug report. The file was indeed badly formatted. This should be much better now.
