### ISSUE TITLE
doesn't work on win 10....stuck on 0%

### ISSUE THREAD

**Issue by ravens202** [elgatosf/streamdeck-cpu#8]
doesn't work on win 10....stuck on 0%

**Comment by Timac** [comment]
@ravens202 Could you try to run the following command:

```
get-counter -Counter "\Processor(_Total)\% Processor Time"
```

You should see an output like this:

```
Timestamp                 CounterSamples
---------                 --------------
2/13/2020 3:15:55 PM      \\pc\processor information(_total)\% processor time :
                          0.443584013304921
```

If you see an error, your registry might be corrupted. You could try to follow the Microsoft support page in this case:
https://support.microsoft.com/en-us/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-6

**Comment by ravens202** [comment]
get-counter "...is not recognized as an internal or external command":
Looking in Performance Monitor window, the current CPU useage is properly displayed.
